include: package:flutter_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - public_member_api_docs
    - sort_constructors_first
    - constant_identifier_names
    - prefer_relative_imports
